# Generated by Django 5.0.4 on 2024-05-05 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=40, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, max_length=30, verbose_name='Отчество')),
                ('date_of_birth', models.DateField(default='', verbose_name='Дата рождения')),
                ('insurance_policy', models.ImageField(blank=True, null=True, upload_to='doc', verbose_name='Копия страхового полиса')),
                ('cost_treatment', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Стоимость лечения')),
            ],
            options={
                'verbose_name': 'Пациент',
                'verbose_name_plural': 'Пациенты',
            },
        ),
        migrations.AddField(
            model_name='disease',
            name='infected',
            field=models.PositiveIntegerField(default=0, verbose_name='Инфицированные'),
        ),
        migrations.AddField(
            model_name='disease',
            name='information',
            field=models.TextField(blank=True, verbose_name='Информация'),
        ),
        migrations.AddField(
            model_name='disease',
            name='is_cure',
            field=models.BooleanField(default=False, verbose_name='Неизлечимая болезнь'),
        ),
        migrations.AddField(
            model_name='disease',
            name='type',
            field=models.CharField(choices=[('viral', 'Вирусные'), ('bacterial', 'Бактериальные'), ('parasitic', 'Паразитарные'), ('fungal', 'Грибковые')], default='Вирусные', max_length=100, verbose_name='Вид'),
        ),
    ]
